name: urcoin
description: urCoin - Decentantralized Wallet App Based on Ethereum Blockchain.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-227.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  ed25519_hd_key: ^2.2.1
  bip39: ^1.0.6
  web3dart: ^2.7.1
  intl_phone_field: ^3.2.0
  coingecko_api: ^1.1.1+1
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  qr_bar_code:
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.0.3
  share_plus: ^7.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env
  
